# Generated by Django 5.2.15 on 2026-06-19 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('slug', models.SlugField(unique=True)),
                ('cover_image', models.ImageField(blank=True, null=True, upload_to='music/covers/')),
                ('genre', models.CharField(blank=True, max_length=150)),
                ('release_date', models.DateField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('spotify_url', models.URLField(blank=True)),
                ('apple_music_url', models.URLField(blank=True)),
                ('audiomack_url', models.URLField(blank=True)),
                ('youtube_url', models.URLField(blank=True)),
                ('boomplay_url', models.URLField(blank=True)),
                ('is_featured', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
