# Generated by Django 5.2.15 on 2026-07-18 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='allow_download',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='music/tracks/'),
        ),
        migrations.AddField(
            model_name='song',
            name='currency',
            field=models.CharField(default='NGN', max_length=10),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='preview_file',
            field=models.FileField(blank=True, null=True, upload_to='music/previews/'),
        ),
        migrations.AddField(
            model_name='song',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='song',
            name='status',
            field=models.CharField(choices=[('stream', 'Stream Only'), ('preorder', 'Pre-order'), ('sale', 'Buy Now'), ('free', 'Free Download')], default='stream', max_length=20),
        ),
    ]
