# Generated by Django 5.2.15 on 2026-08-09 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='albums/tracks/'),
        ),
        migrations.AddField(
            model_name='track',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
