# Generated by Django 5.2.15 on 2026-08-10 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_track_audio_file_track_is_published'),
        ('store', '0005_product_featured'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='products',
            field=models.ManyToManyField(blank=True, related_name='albums', to='store.product'),
        ),
    ]
